spring.application.name=AiDeepfake-Detector

# Server Port
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/deepfake_detector
spring.datasource.username=****
spring.datasource.password=****
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Sightengine
# Sightengine
sightengine.api.user=20920835
sightengine.api.secret=vonAAdbgD8zHWjGggEQX7BdaMHXjhqiY
# Gemini
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

gemini.api.key=AIzaSyBSm42STmrNm3YTweiL_Zmr_fLfpAI5wgk